package com.ezrachai.gmailclone

import com.ezrachai.gmailclone.model.MailData
import com.ezrachai.gmailclone.model.PersonalEmailData

val emailList = listOf(
    MailData(1, "alice", "Meeting Reminder", "Don't forget our meeting at 10am.", "08:15"),
    MailData(2, "bob", "Invoice Attached", "Please find the invoice attached.", "09:22"),
    MailData(3, "carol", "Greetings!", "Hope you are having a great day.", "10:05"),
    MailData(4, "dave", "Project Update", "The project is on track for completion.", "11:30"),
    MailData(5, "eve", "Invitation", "You are invited to our annual event.", "12:45"),
    MailData(6, "frank", "Newsletter", "Here is your monthly newsletter.", "13:10"),
    MailData(7, "grace", "Your Order", "Your order has been shipped.", "14:25"),
    MailData(8, "heidi", "Account Alert", "There was a login from a new device.", "15:40"),
    MailData(9, "ivan", "Welcome!", "Welcome to our service!", "16:55"),
    MailData(10, "judy", "Thank You", "Thank you for your feedback.", "17:20"),
    MailData(11, "alice", "Password Reset", "Click here to reset your password.", "18:33"),
    MailData(12, "bob", "Event Reminder", "Don't forget the event tomorrow.", "19:44"),
    MailData(13, "carol", "Survey", "Please take a moment to fill our survey.", "20:01"),
    MailData(14, "dave", "Promotion", "Check out our latest promotions.", "21:12"),
    MailData(15, "eve", "Security Notice", "Your account security is important.", "22:23"),
    MailData(16, "frank", "Update Available", "A new update is available.", "23:34"),
    MailData(17, "grace", "Subscription", "Your subscription has been renewed.", "00:45"),
    MailData(18, "heidi", "Billing Info", "Your billing information was updated.", "01:56"),
    MailData(19, "ivan", "Support", "How can we help you today?", "02:07"),
    MailData(20, "judy", "Order Confirmation", "Your order is confirmed.", "03:18"),
    MailData(21, "alice", "Shipping Update", "Your package is out for delivery.", "04:29"),
    MailData(22, "bob", "Receipt", "Here is your receipt.", "05:40"),
    MailData(23, "carol", "Feedback Request", "We value your feedback.", "06:51"),
    MailData(24, "dave", "Account Update", "Your account has been updated.", "07:02"),
    MailData(25, "eve", "Welcome Back", "We missed you! Welcome back.", "08:13"),
    MailData(26, "frank", "Newsletter", "Here is your weekly newsletter.", "09:24"),
    MailData(27, "grace", "Order Shipped", "Your order is on its way.", "10:35"),
    MailData(28, "heidi", "Password Changed", "Your password was changed.", "11:46"),
    MailData(29, "ivan", "Event Invitation", "Join us for our next event.", "12:57"),
    MailData(30, "judy", "Thank You", "Thank you for your purchase.", "13:08"),
    MailData(31, "alice", "Reminder", "This is a friendly reminder.", "14:19"),
    MailData(32, "bob", "Invoice", "Your invoice is attached.", "15:30"),
    MailData(33, "carol", "Greetings", "Wishing you a wonderful day.", "16:41"),
    MailData(34, "dave", "Project Status", "Project status has been updated.", "17:52"),
    MailData(35, "eve", "Invitation", "You are invited to our webinar.", "18:03"),
    MailData(36, "frank", "Newsletter", "Monthly newsletter attached.", "19:14"),
    MailData(37, "grace", "Order Delivered", "Your order has been delivered.", "20:25"),
    MailData(38, "heidi", "Account Alert", "Suspicious activity detected.", "21:36"),
    MailData(39, "ivan", "Welcome!", "Welcome to our platform.", "22:47"),
    MailData(40, "judy", "Thank You", "Thank you for your loyalty.", "23:58"),
    MailData(41, "alice", "Password Reset", "Reset your password here.", "00:09"),
    MailData(42, "bob", "Event Reminder", "Event starts at 6pm.", "01:20"),
    MailData(43, "carol", "Survey", "We appreciate your input.", "02:31"),
    MailData(44, "dave", "Promotion", "Special offer just for you.", "03:42"),
    MailData(45, "eve", "Security Notice", "Please verify your identity.", "04:53"),
    MailData(46, "frank", "Update Available", "Update your app now.", "05:04"),
    MailData(47, "grace", "Subscription", "Subscription renewed.", "06:15"),
    MailData(48, "heidi", "Billing Info", "Billing info updated.", "07:26"),
    MailData(49, "ivan", "Support", "Contact us for support.", "08:37"),
    MailData(50, "judy", "Order Confirmation", "Order confirmed.", "09:48")
)

val personalEmail = listOf(
    PersonalEmailData("Chris Morty", "chris@gmail.com", 83),
    PersonalEmailData("Christy Jane", "jane@gmail.com", 139),
)
